Algoritmo "Exercicio 15"
// Disciplina   : Lógica de Programação
// Professor   : Obama
// Descrição   : 15) Ler um valor e escrever se é positivo ou negativo
//(considere o valor zero como positivo
// Autor(a)    : Alexandre Lemes
// Data atual  : 05/09/2023
Var
   valor:inteiro

Inicio
   Escreva("Digite um valor:")
   Leia(valor)

   Se valor>=0 entao
      Escreva("POSITIVO")
   senao
      Escreva("NEGATIVO")
   fimse
Fimalgoritmo