Algoritmo "Antecessor"
// Disciplina   : Lógica de Programação
// Professor   : Obama
// Descrição   : 5) Escreva um algoritmo para ler um valor (do teclado) e
//escrever (na tela) o seu antecessor.
// Autor(a)    : Alexandre Lemes
// Data atual  : 05/09/2023
Var
   valor:inteiro

Inicio
   Escreva("Digite um valor:")
   Leia(valor)
   Escreva("O antecessor do numero", valor, " é", valor-1)
Fimalgoritmo