Algoritmo "semnome"
// Disciplina   : Lógica de Programação
// Professor   : Obama
// Descrição   : 55) Escreva um algoritmo que calcule e imprima a tabuada do 8
//(1 a 10).
// Autor(a)    : Alexandre Lemes
// Data atual  : 20/09/2023
Var
   // Seção de Declarações das variáveis
   numero:inteiro

Inicio
   // Seção de Comandos, procedimento, funções, operadores, etc...
   para numero de 1 ate 10 passo 1 faça
      Escreval(numero," X 8 =", numero*8)
   fimpara

Fimalgoritmo